ass_header = '''[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: YYeTs
Original Script: YYeTs
Original Translation: 
Original Timing: 
Original Editing: 
Script Updated By: 
Update Details: 
ScriptType: v4.00+
PlayResX: 384
PlayResY: 288
Timer: 100.0000
Synch Point: 0
WrapStyle: 0
ScaledBorderAndShadow: no

[Aegisub Project Garbage]
Scroll Position: 1283
Active Line: 1322

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,FZHei-B01,19,&H00FFFFFF,&HF0000000,&H00000000,&H32000000,-1,0,0,0,100,100,0,0,1,0,1,2,5,5,2,134

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
'''

def get_header():
    return ass_header